### ISSUE TITLE
More information needed regarding logging

### ISSUE THREAD

**Issue by ryn9** [f5devcentral/f5-telemetry-streaming#1]
Example provided were enough to install and get the system poller functional.

What is not clear is how to configure the F5 Bigip for the following logging:
LTM Request Log
AFM Request Log
ASM Request Log
APM Request Log

I *believe* that logging needs to be done to provisioned "listener", but there is no information provided on what is required.

**Comment by jsevedge** [comment]
This is fixed in the v1.0.0 release, i would start with the following section :)

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/userguide/event-listener.html
