### ISSUE TITLE
standardize date and time in output

### ISSUE THREAD

**Issue by ryn9** [f5devcentral/f5-telemetry-streaming#2]
The different example outputs have various different date and time fields and different formats.

Please standardize the field name and adopt ISO 8601 for the time timestamp format.

**Comment by jsevedge** [comment]
@ryn9 Good thought, currently TS leaves the timestamp as is according to how it was retrieved. However normalizing it would be valuable.  Internal ID is 89.

**Comment by jsevedge** [comment]
This is being tracked via the new repo here: https://github.com/F5Networks/f5-telemetry-streaming/issues/4
