### ISSUE TITLE
Add support for additional consumers

### ISSUE THREAD

**Issue by ryn9** [f5devcentral/f5-telemetry-streaming#3]
Please provide options to output for additional consumers.

For example:
Kafka
Elastic Search / Logstash
Redis
Generic http/https

**Comment by jsevedge** [comment]
@ryn9 Kafka and elastic search are targeted for our next release of TS.  Issues created to track adding support for Redis and generic http created, internal ID's respectively 87 and 88.

Is direct elastic search consumer sufficient or do you also have a specific requirement for logstash?

If you have any additional input on either of these that should drive how the consumer is created please let us know.

**Comment by jsevedge** [comment]
This issue is being tracked in the new repo here: https://github.com/F5Networks/f5-telemetry-streaming/issues/3
