### ISSUE TITLE
Telemetry data is send to wrong graphite uri

### ISSUE THREAD

**Issue by RemcoAA** [f5devcentral/f5-telemetry-streaming#4]
Hi,
I am testing F5 telemetry to send data to Graphite but events are not accepted on Graphite server.
F5 is POSTing the JSON call to **/events** while according to Graphite documentation (https://graphite.readthedocs.io/en/latest/events.html) it should be to **/events/**

If I POST the JSON file I captured with a tcpdump using Postman, towards /events/ the events show up in the Graphite events dashboard.

**Comment by jsevedge** [comment]
Hello, @RemcoAA this was tested prior to the last release with no issues.  Which version of graphite are you using?

Also, does anything standout in /var/log/restnoded/restnoded.log?  I assume Graphite is responding with an error status code and message?

**Comment by jsevedge** [comment]
Internal ID 102 created to track this.

**Comment by jsevedge** [comment]
As mentioned it worked during testing in my local environment, however it worked against /events/ as well and graphite includes trailing / so this will be fixed and released with the next version.

**Comment by jsevedge** [comment]
This is fixed in the v1.0.0 release, please feel free to reopen if you run into this issue again.
