### ISSUE TITLE
IPSEC tunnel status and statistics

### ISSUE THREAD

**Issue by rmuermann** [f5devcentral/f5-telemetry-streaming#6]
- Feature Idea

Can IPSEC tunnel status and all available tunnel statistics be collected and streamed to a monitor service, such as Azure Monitor?  The statistics are all available via iControl REST, so it should be easy to pull it into TS.

https://{mgmt ip}/mgmt/tm/net/tunnels/tunnel/\~Common\~{tunnel name}/stats

**Comment by jsevedge** [comment]
Sounds like a great request!  Internal ID created to track this: 124

**Comment by jsevedge** [comment]
This is being tracked in the new repo here: https://github.com/F5Networks/f5-telemetry-streaming/issues/2
